config/routes.rb
Rails.application.routes.draw do

  resources :lists
  get 'likes/create'

  get 'likes/destroy'

  get 'favourites/create'

  get 'favourite/create'

  devise_for :suppliers
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'suppliers/:id' => 'suppliers#destroy', :via => :delete, :as => :admin_destroy_supplier

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :sub_categories do
      resources :products do
        resources :favourites, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]

        resources :product_comments, only: [:create]
      end
    end
  end


  resources :order_items
  resource :carts, only: [:show]
  resources :users, only: [:show]
  resources :suppliers, only: [:show, :index] do
    resources :lists
    resources :supplier_comments, only: [:create]
  end



  get '/descuentos', to: 'categories#descuentos', as: 'descuentos'


  get '/alfa', to: 'pages#alfa', as: 'alfa'
  get '/contactanos', to: 'pages#contact', as: 'contact'
  get '/quienessomos', to: 'pages#about', as: 'about'
  get '/administrador', to: 'pages#admin', as: 'admin'
  get '/cate_list', to: 'pages#cate_list', as: 'cate_list'
  get '/produ_list', to: 'pages#produ_list', as: 'produ_list'
  get '/mis_productos', to: 'suppliers#my_products', as: 'my_products'
  get '/user_list', to: 'pages#user_list', as: 'user_list'
  get '/suppli_list', to: 'pages#suppli_list', as: 'suppli_list'
  get '/blog', to: 'pages#blog', as: 'blog'

  get '/choose', to: 'products#choose', as: 'choose'

  root 'categories#index'

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id            :integer          not null, primary key
#  title         :string
#  supplier_id   :integer
#  free_shipping :boolean
#  promotion     :boolean
#  quantity      :boolean
#  price         :boolean
#  q2            :integer
#  q1            :integer
#  q3            :integer
#  q4            :integer
#  p_q1          :float
#  p_q2          :float
#  p_q3          :float
#  p_q4          :float
#  p1            :float
#  p2            :float
#  p3            :float
#  p4            :float
#  p_p1          :float
#  p_p2          :float
#  p_p3          :float
#  p_p4          :float
#  sq1           :integer
#  sq2           :integer
#  sq3           :integer
#  sq4           :integer
#  sp_q1         :float
#  sp_q2         :float
#  sp_q3         :float
#  sp_q4         :float
#  sp1           :float
#  sp2           :float
#  sp3           :float
#  sp4           :float
#  sp_p1         :float
#  sp_p2         :float
#  sp_p3         :float
#  sp_p4         :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_lists_on_supplier_id  (supplier_id)
#

class List < ApplicationRecord
  belongs_to :supplier
  has_many :products, dependent: :delete_all
  has_many :list_groups, dependent: :delete_all

  accepts_nested_attributes_for :products 

  validates :title, presence: true
  validate :quantity_cannot_be_less_than_previous_quantity
  validate :price_cannot_be_less_than_previous_price
  validate :discount_and_shipping_exist

  def quantity_cannot_be_less_than_previous_quantity
    error=false
    if q1.present? || q2.present? || q3.present? || q4.present?
      quantities = [q1,q2,q3,q4]
      3.times do |i|
        if (quantities[i].present?) && (quantities[i+1].present?)
          if quantities[i].to_i >= quantities[i+1].to_i
            error = true
          end
        end
        if ( not quantities[i].present?) && (quantities[i+1].present?)
          error = true
        end
      end
      if (error == true) then errors.add(:quantity, "Rango por cantidades mal organizado. Verifique que el siguente valor sea mayor al anterior") end
    end
  end

  def price_cannot_be_less_than_previous_price
    error=false
    if p1.present? || p2.present? || p3.present? || p4.present?
      prices = [p1,p2,p3,p4]
      3.times do |i|
        if (prices[i].present?) && (prices[i+1].present?)
          if prices[i].to_i >= prices[i+1].to_i
            error = true
          end
        end
        if ( not prices[i].present?) && (prices[i+1].present?)
          error = true
        end
      end
      if (error == true) then errors.add(:price, "Rango por precios mal organizado. Verifique que el siguente valor sea mayor al anterior") end
    end
  end

  def discount_and_shipping_exist
    if promotion && quantity
      if (q1.present?) && (not p_q1.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
      if (q2.present?) && (not p_q2.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
      if (q3.present?) && (not p_q3.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
      if (q4.present?) && (not p_q4.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
    end
    if promotion && price
      if (p1.present?) && (not p_p1.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
      if (p2.present?) && (not p_p2.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
      if (p3.present?) && (not p_p3.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
      if (p4.present?) && (not p_p4.present?) then errors.add(:promotion, "Verifique que para cada rango tiene su descuento") end
    end
    if (not free_shipping) && quantity
      if (q1.present?) && (not sp_q1.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
      if (q2.present?) && (not sp_q2.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
      if (q3.present?) && (not sp_q3.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
      if (q4.present?) && (not sp_q4.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
    end
    if (not free_shipping) && price
      if (p1.present?) && (not sp_p1.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
      if (p2.present?) && (not sp_p2.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
      if (p3.present?) && (not sp_p3.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
      if (p4.present?) && (not sp_p4.present?) then errors.add(:free_shipping, "Verifique que para cada rango tiene su costo de envío") end
    end

  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @supplier = current_supplier
    @lists = Supplier.find(params[:supplier_id]).lists
  end

  def new
    @list = List.new()
  end

  def create
    puts(params)
    puts("<---------------------")
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = 'Se creó la lista exitosamente'
      redirect_to supplier_lists_path(current_supplier)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to supplier_lists_path(current_supplier)
    else
      render :edit
    end
  end

  def destroy
    @List = List.find(params[:id])
    @List.destroy

    redirect_to request.referrer
  end

  private

    def list_params
      params.require(:list).permit(:title, :supplier_id, :free_shipping, :promotion, :quantity, :price, :q1, :q2, :q3, :q4, :p_q1, :p_q2, :p_q3, :p_q4, :p1, :p2, :p3, :p4, :p_p1, :p_p2, :p_p3, :p_p4, :sq1, :sq2, :sq3, :sq4, :sp_q1, :sp_q2, :sp_q3, :sp_q4, :sp1, :sp2, :sp3, :sp4, :sp_p1, :sp_p2, :sp_p3, :sp_p4)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/edit.html.erb
<h3>Editar descuento mayorista y envíos</h3>
<%= form_for @list, url: supplier_list_path(@list) do |f| %>

<% if @list.errors.any? %>
  <% @list.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

<%= f.hidden_field :supplier_id, :value => current_supplier.id %>

<div class="field">
  Título
  <%= f.text_field :title, autofocus: true%> <br> <br>
  <%= f.check_box :free_shipping, class: "check-free-shipping"%> Envíos gratis</br></br>
</div>
<div class="field">
  <%= f.check_box :promotion, class: "check-discount-range"%> Utilizar descuentos por rango</br></br>
</div>

<div class="field">
  Organizar rangos por: <%= f.check_box :quantity, class: "check-quantity"%> Cantidad       <%= f.check_box :price, class: "check-price"%> Precio     </br></br>
</div>
<div class="field">
  <h4 class="no-discount-no-shipping">Precio fijo sin costos de envío</h4>
  <table class="table table-of-prices">
    <thead>
      <tr>
        <th scope="col">Rango por precio</th>
        <th scope="col" class= "discount-col">Descuento</th>
        <th scope="col" class= "shipping-col">Precio</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p1, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p1, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p1, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p2, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p2, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p2, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p3, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p3, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p3, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p4, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p4, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p4, autofocus: true %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="field">
  <table class="table table-of-quantity">
    <thead>
      <tr>
        <th scope="col">Rango por cantidad</th>
        <th scope="col"class= "discount-col">Descuento</th>
        <th scope="col"class= "shipping-col">Precio</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Compras mayores a <%=f.number_field :q1, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q1, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q1, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a <%=f.number_field :q2, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q2, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q2, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a <%=f.number_field :q3, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q3, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q3, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a <%=f.number_field :q4, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q4, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q4, autofocus: true %></td>
      </tr>
    </tbody>
  </table>
</div>
<%=f.submit "Editar lista"%>
<%end%>

<script>
   new ListForm();
</script>

app/views/lists/index.html.erb
<h1>Acá se emostrarán las listas</h1>
<%puts(current_supplier.id)%>
<% if supplier_signed_in? && current_supplier.id == @supplier.id%>
  <%=link_to "Nueva lista", new_supplier_list_path%> <br><br>
  <%end%>

<%@lists.each do |list|%>
  <%if (list.free_shipping ==true )&&(list.promotion == false)%>
    <h3><%=list.title%></h3>
    <% if supplier_signed_in? && current_supplier.id == @supplier.id%>
      <%=link_to "Editar", edit_supplier_list_path(current_supplier,list)%>
      <%= link_to "Eliminar", list, method: :delete, data: { confirm: '¿Estás seguro de eliminar este producto?' } %>
    <%end%>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Rango por cantidad</th>
          <th scope="col">Procentaje de descuento</th>
          <th scope="col">Costo de envío</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Para todas las cantidades</td>
          <td>Precio único</td>
          <td>Gratis</td>
        </tr>
      </tbody>
    </table>
  <%else%>
    <h3><%=list.title%></h3>
    <% if supplier_signed_in? && current_supplier.id == @supplier.id%>
      <%=link_to "Editar", edit_supplier_list_path(current_supplier,list)%>
      <%= link_to "Eliminar", list, method: :delete, data: { confirm: '¿Estás seguro de eliminar este producto?' } %>
    <%end%>
    <%if list.quantity == true%>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Rango por cantidad</th>
            <th scope="col">Procentaje de descuento</th>
            <th scope="col">Costo de envío</th>
          </tr>
        </thead>
        <tbody>
          <%if list.q1 != nil%>
          <tr>
            <td><%=list.q1%> unidades</td>
            <td><%= (list.promotion == true) ? (list.p_q1).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_q1).to_s : "Gratis"%></td>
          </tr>
          <%end%>
          <%if list.q2 != nil%>
          <tr>
            <td><%=list.q2%> unidades</td>
            <td><%= (list.promotion == true) ? (list.p_q2).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_q2).to_s : "Gratis"%></td>
          </tr>
          <%end%>
          <%if list.q3 != nil%>
          <tr>
            <td><%=list.q3%> unidades</td>
            <td><%= (list.promotion == true) ? (list.p_q3).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_q3).to_s : "Gratis"%></td>
          </tr>
          <%end%>
          <%if list.q3 != nil%>
          <tr>
            <td><%=list.q4%> unidades</td>
            <td><%= (list.promotion == true) ? (list.p_q4).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_q4).to_s : "Gratis"%></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    <%else%>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Rango por precio</th>
            <th scope="col">Procentaje de descuento</th>
            <th scope="col">Costo de envío</th>
          </tr>
        </thead>
        <tbody>
          <%if list.p1 != nil%>
          <tr>
            <td>$<%=list.p1%></td>
            <td><%= (list.promotion == true) ? (list.p_p1).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_p1).to_s : "Gratis"%></td>
          </tr>
          <%end%>
          <%if list.p2 != nil%>
          <tr>
            <td>$<%=list.p2%></td>
            <td><%= (list.promotion == true) ? (list.p_p2).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_p2).to_s : "Gratis"%></td>
          </tr>
          <%end%>
          <%if list.p3 != nil%>
          <tr>
            <td>$<%=list.p3%></td>
            <td><%= (list.promotion == true) ? (list.p_p3).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_p3).to_s : "Gratis"%></td>
          </tr>
          <%end%>
          <%if list.p4 != nil%>
          <tr>
            <td>$<%=list.p4%></td>
            <td><%= (list.promotion == true) ? (list.p_p4).to_s+"%" : "Costo fijo"%></td>
            <td><%= (list.free_shipping == false) ? "$"+(list.sp_p4).to_s : "Gratis"%></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    <%end%>
  <%end%>

<%end%>

app/views/lists/new.html.erb
<h3>Descuentos mayoristas y envíos</h3>
<% if @list.errors.any? %>
  <% @list.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%= form_for @list, url: supplier_lists_path do |f| %>

<%= f.hidden_field :supplier_id, :value => current_supplier.id %>

<div class="field">
  Título
  <%= f.text_field :title, autofocus: true%> <br> <br>
  <%= f.check_box :free_shipping, class: "check-free-shipping"%> Envíos gratis</br></br>
</div>
<div class="field">
  <%= f.check_box :promotion, class: "check-discount-range"%> Utilizar descuentos por rango</br></br>
</div>

<div class="field">
  Organizar rangos por: <%= f.check_box :quantity, checked: true, class: "check-quantity"%> Cantidad       <%= f.check_box :price, class: "check-price"%> Precio     </br></br>
</div>
<div class="field">
  <h4 class="no-discount-no-shipping">Precio fijo sin costos de envío</h4>
  <table class="table table-of-prices">
    <thead>
      <tr>
        <th scope="col">Rango por precio</th>
        <th scope="col" class= "discount-col">Descuento</th>
        <th scope="col" class= "shipping-col">Precio</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p1, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p1, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p1, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p2, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p2, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p2, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p3, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p3, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p3, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a $<%=f.number_field :p4, autofocus: true%></td>
        <td class = "discount-col"><%=f.number_field :p_p4, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_p4, autofocus: true %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="field">
  <table class="table table-of-quantity">
    <thead>
      <tr>
        <th scope="col">Rango por cantidad</th>
        <th scope="col"class= "discount-col">Descuento</th>
        <th scope="col"class= "shipping-col">Precio</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Compras mayores a <%=f.number_field :q1, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q1, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q1, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a <%=f.number_field :q2, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q2, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q2, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a <%=f.number_field :q3, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q3, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q3, autofocus: true %></td>
      </tr>
      <tr>
        <td>Compras mayores a <%=f.number_field :q4, autofocus: true%> unidades</td>
        <td class = "discount-col"><%=f.number_field :p_q4, autofocus: true%>%</td>
        <td class = "shipping-col">$<%=f.number_field :sp_q4, autofocus: true %></td>
      </tr>
    </tbody>
  </table>
</div>
<%=f.submit "Crear lista"%>
<%end%>

<script>
   new ListForm();
</script>