config/routes.rb
Rails.application.routes.draw do

  resources :lists
  get 'likes/create'

  get 'likes/destroy'

  get 'favourites/create'

  get 'favourite/create'

  devise_for :suppliers
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'suppliers/:id' => 'suppliers#destroy', :via => :delete, :as => :admin_destroy_supplier

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :sub_categories do
      resources :products do
        resources :favourites, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]

        resources :product_comments, only: [:create]
      end
    end
  end


  resources :order_items
  resource :carts, only: [:show]
  resources :users, only: [:show]
  resources :suppliers, only: [:show, :index] do
    resources :lists
    resources :supplier_comments, only: [:create]
  end



  get '/descuentos', to: 'categories#descuentos', as: 'descuentos'


  get '/alfa', to: 'pages#alfa', as: 'alfa'
  get '/contactanos', to: 'pages#contact', as: 'contact'
  get '/quienessomos', to: 'pages#about', as: 'about'
  get '/administrador', to: 'pages#admin', as: 'admin'
  get '/cate_list', to: 'pages#cate_list', as: 'cate_list'
  get '/produ_list', to: 'pages#produ_list', as: 'produ_list'
  get '/mis_productos', to: 'suppliers#my_products', as: 'my_products'
  get '/user_list', to: 'pages#user_list', as: 'user_list'
  get '/suppli_list', to: 'pages#suppli_list', as: 'suppli_list'
  get '/blog', to: 'pages#blog', as: 'blog'

  get '/choose', to: 'products#choose', as: 'choose'

  root 'categories#index'

end

app/views/pages/about.html.erb
<h1>¿Quiénes somos?</h1>

app/views/pages/admin.html.erb
<h1>Opciones de administrador</h1>

<%= link_to new_category_path, class: "admin-link" do%>
  <button type="button" name="button">Crear categoría</button>
<%end%>

<%= link_to user_list_path, class: "admin-link" do%>
  <button type="button" name="button">Ver usuarios registrados</button>
<%end%>

<%= link_to suppli_list_path, class: "admin-link" do%>
  <button type="button" name="button">Ver proveedores registrados</button>
<%end%>

<%= link_to produ_list_path, class: "admin-link" do%>
  <button type="button" name="button">Mostrar productos</button>
<%end%>

<%= link_to cate_list_path, class: "admin-link" do%>
  <button type="button" name="button">Mostrar categorías</button>
<%end%>

<script>
  new DeleteActiveClass();
  new DeleteActiveLinkClass();
  new AddAdminActiveClass();
</script>

app/views/pages/alfa.html.erb
<h1><b>Seguimiento del desarrollo</b></h1>


<h3><b>Ventanas y accesos:</b></h3>
<img src="https://drive.google.com/uc?export=view&id=1sup3e_hlg_NC-eTHqDvVaHcgFuH_tqag" class="seguimiento">

<h3><b>Funcionalidades por ventanas:</b></h3>
<img src="https://drive.google.com/uc?export=view&id=1xOfCDLp8LA-zgyjCln9fbyYqYkXyu_8O" class="commits">

<h3><b>Estructura de la base de datos:</b></h3>
<img src="https://drive.google.com/uc?export=view&id=1tbkYhbbcphT5C46QlOGzWDHHw6rRPyVk" class="seguimiento">


<h3><b>Commits por día:</b></h3>
<!-- <img src="https://drive.google.com/uc?export=view&id=1ACvnFa09fQks1UOB1G2jnRFgR4PQjywz" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1eVIdMvv7cICy5nKdy0mxhuc-Cz-MG6Y3" class="commits"> -->
<img src="https://drive.google.com/uc?export=view&id=1cz-6dAXEQ6IfQlcqLLXgMRTr9OKdN0HR" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1BG2yLOImtHnQEurShAj8W0aTVokImznG" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1H3wW80wdo8szO9OKHJ8Xc7T-JsUIBr7H" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1dbeeEas28gO-SfosfWSSMi4Az9IIQmvt" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1APn5hDw8EckuuDt9KXcWSXswbrryDw6a" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1gLP_5TozCnEV_FPeFG_GoQZC1BO4czPM" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1Wr3waxMENEQ3Cdy5rBOsbfIhmjTSwH5L" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1nM4VYt88YPBrXEPI4D4Nms8Sxv3mVz70" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1u49ggj7yvFtGTGTP3uVU66BXbJKnyqsU" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1KTahxMhTzHj23Ep2dboIOjzrBP7B0a4i" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1Z-ayaxeTdzxNiWRwObuijOcqjUTbJ0qm" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1juKNZnbpA8ar9gyOmb57DoymD_rzLO6K" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1Gm0qX-_fP96jn85lW9KXtVsTQlYpNyN1" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1t7Cgo9V1a714C2bgeVQLSC8TuhKIywyz" class="commits">
<img src="https://drive.google.com/uc?export=view&id=1STR2iVWz3k5nqjV_qr_1_zCHOZHIANNB" class="commits">

app/views/pages/blog.html.erb
<div class="blog-content">
  <div class="blog-post">
    <h4>¡Chaquetas y Abrigos! Mira como cubrirte con estilo durante lo que resta de año</h4>
    <p>24 Oct 2017 | Emily Savino </p>
    <img src="https://static.wixstatic.com/media/82c2c1_0f15b4faafab47089a59ea9e371e32d6~mv2.jpg/v1/fill/w_780,h_540,al_c,lg_1,q_85/82c2c1_0f15b4faafab47089a59ea9e371e32d6~mv2.webp" >
    <p>Las chaquetas son una prenda básica tanto para hombres como para mujeres, sobre todo, son especialmente útiles durante la temporada de otoño e invierno, cuando bajan las temperaturas y el frió amenaza con convertirnos en cubos de hielo. Son un e...</p>
    <button>Leer más</button>
  </div>

  <div class="blog-post">
    <h4>TIPO POLO: Una Prenda para toda Ocasión!!</h4>
    <p>18 Oct 2017 | Diego A. Aguirre</p>
    <img src="https://static.wixstatic.com/media/82c2c1_17bc5a3dab29409b940cbc351d022d6c~mv2.jpg/v1/fill/w_866,h_487,al_c,q_85,usm_0.66_1.00_0.01/82c2c1_17bc5a3dab29409b940cbc351d022d6c~mv2.webp" >
    <p>Obligatoria en los armarios de todos los hombres. Fresca, clásica y para toda ocasión. Así se puede definir una prenda que desde tiempos memorables ha acompañado al hombre y que inicialmente se creo para uniformar a los equipos que practicaban este deporte. El polo...</p>
    <button>Leer más</button>
  </div>

  <div class="blog-post">
    <h4>3 principios de una negociación efectiva</h4>
    <p>23 Oct 2017 | Emprendedores </p>
    <img src="https://static.wixstatic.com/media/82c2c1_6b4d5aefe9fe48a8a534243cd3e39a0e~mv2.jpg/v1/fill/w_866,h_865,al_c,q_85,usm_0.66_1.00_0.01/82c2c1_6b4d5aefe9fe48a8a534243cd3e39a0e~mv2.webp" >
    <p>Desde un reembolso hasta conseguir un socio, todo es negociación, ¿sabes aprovechar tus habilidades? Te damos las claves para ganar</p>

    <p>Negociar es una de las habilidades que marcan la diferencia entre un empresario exitoso y otro que no logra hacer crecer su empresa. Una n...</p>
    <button>Leer más</button>
  </div>

  <div class="blog-post">
    <h4>LOOK TOTAL DENIM PARA EL ENTRETIEMPO</h4>
    <p>3 Oct 2017 | Javier Ollero </p>
    <img src="https://static.wixstatic.com/media/82c2c1_0db8e328955f4502a524d078845165c9~mv2.jpg/v1/fill/w_640,h_587,al_c,q_85/82c2c1_0db8e328955f4502a524d078845165c9~mv2.webp" >
    <p>Aunque últimamente estamos viendo mucha repetición de colores y estampados, hay que tener cuidado a la hora de crear un total look vaquero. La mejor opción, sin complicaciones, se consigue escogiendo un pantalón y cazadora con similares colores y desgastes. En cuanto a...</p>

    <button>Leer más</button>
  </div>
</div>

<script>
  new DeleteActiveClass();
  new DeleteActiveLinkClass();
  new AddBlogActiveClass();
</script>

app/views/pages/cate_list.html.erb
<div class="container">
  <h1>Categorías</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Imagen</th>
        <th scope="col">Nombre</th>
        <th scope="col">Productos disponibles</th>
        <th scope="col">Sub categorías</th>
        <th scope="col">Editar</th>
        <th scope="col">Eliminar</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category|%>
        <tr>
          <th><img src="<%=category.img_url%>" class="mini-img"></th>
          <td><%=category.title%></td>
          <td>
            <%produ=0%>
            <%category.sub_categories.each do |subcategory|%>
              <%subcategory.products.each do |product|%>
                <%produ = produ + product.xs + product.s + product.m + product.l + product.xl + product.xxl%>
              <%end%>
            <%end%>

            <%=produ%>
          </td>
          <td>
            <%category.sub_categories.each do |subcategory|%>
              <%=subcategory.title%> -
            <%end%>
          </td>
          <td>
            <%=link_to edit_category_path(category) do%>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <%end%>
          </td>
          <td>
            <%=link_to category_path(category), method: :delete, data:{ confirm: "Si elimina esta categoría puede que ocurra fallas en la barra de navegación. ¿Está seguro que desea continuar?"} do%>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>

</div>

app/views/pages/contact.html.erb
<h1>Contáctanos</h1>

app/views/pages/ecommerce.html.erb
<h1>Viedo y animaciones</h1>

app/views/pages/produ_list.html.erb
<div class="container">
  <h1>Productos</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Imagen</th>
        <th scope="col">Categoría</th>
        <th scope="col">Nombre</th>
        <th scope="col">Cantidad disponible</th>
        <th scope="col">Editar</th>
        <th scope="col">Eliminar</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product|%>
      <%if product.supplier.id == current_supplier.id%>
        <tr>
          <th>
            <%=link_to [product.sub_category.category, product.sub_category, product] do%>
              <img src="<%=product.img_url%>" class="mini-img">
            <%end%>

          </th>
          <td><%=product.sub_category.category.title%></td>
          <td><%=product.title%></td>
          <td><%=(product.check_unique == true) ? (produ = product.unique) : (produ = product.q1 + product.q2 + product.q3 + product.q4 + product.q5 + product.q6 + product.q7 + product.q8 + product.q9 + product.q10)%></td>
          <td>
            <%=link_to edit_category_sub_category_product_path(product.sub_category.category, product.sub_category, product) do%>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <%end%>
          </td>
          <td>
            <%=link_to [product.sub_category.category, product.sub_category, product], method: :delete, data:{ confirm: "¿Está seguro de eliminar este producto?"} do%>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <%end%>

          </td>
        </tr>
      <%end%>
      <%end%>
    </tbody>
  </table>
</div>

app/views/pages/suppli_list.html.erb
<div class="container">
  <h1>Proveedores registrados (<%=@suppliers.length%>)</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Email</th>
        <th scope="col"># de productos</th>
        <th scope="col">Fecha de registro</th>
        <th scope="col">Detalles proveedor</th>
        <th scope="col">Eliminar proveedor</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier|%>
        <tr>
          <th><%=supplier.full_name%></th>
          <th><%=supplier.email%></th>
          <th>
            <%=supplier.products.length%>
          </th>
          <td><%=supplier.created_at%></td>
          <td><%=link_to supplier_path(supplier) do%>
            <i class="fa fa-info-circle" aria-hidden="true"></i>
          <%end%>
          </td>
          <td><%= link_to admin_destroy_supplier_path(supplier), method: :delete, data: { confirm: "¿Estás seguro de eliminar este proveedor?" } do%>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>

</div>

app/views/pages/user_list.html.erb
<h1>Usuarios registrados (<%=@users.length%>)</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Email</th>
      <th scope="col"># de productos comprados</th>
      <th scope="col">Fecha de registro</th>
      <th scope="col">Último ingreso</th>
      <th scope="col"># de visitas</th>
      <th scope="col">Detalles usuario</th>
      <th scope="col">Eliminar usuario</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|%>
      <tr>
        <td><%=user.full_name%></td>
        <td><%=user.email%></td>
        <td><%=user.purchases%></td>
        <td><%=user.created_at%></td>
        <td><%=user.updated_at%></td>
        <td><%=user.sign_in_count%></td>
        <td><%=link_to user_path(user) do%>
          <i class="fa fa-info-circle" aria-hidden="true"></i>
        <%end%>
        <td><%= link_to admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } do%>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <%end%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>