config/routes.rb
Rails.application.routes.draw do

  resources :lists
  get 'likes/create'

  get 'likes/destroy'

  get 'favourites/create'

  get 'favourite/create'

  devise_for :suppliers
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'suppliers/:id' => 'suppliers#destroy', :via => :delete, :as => :admin_destroy_supplier

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :sub_categories do
      resources :products do
        resources :favourites, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]

        resources :product_comments, only: [:create]
      end
    end
  end


  resources :order_items
  resource :carts, only: [:show]
  resources :users, only: [:show]
  resources :suppliers, only: [:show, :index] do
    resources :lists
    resources :supplier_comments, only: [:create]
  end



  get '/descuentos', to: 'categories#descuentos', as: 'descuentos'


  get '/alfa', to: 'pages#alfa', as: 'alfa'
  get '/contactanos', to: 'pages#contact', as: 'contact'
  get '/quienessomos', to: 'pages#about', as: 'about'
  get '/administrador', to: 'pages#admin', as: 'admin'
  get '/cate_list', to: 'pages#cate_list', as: 'cate_list'
  get '/produ_list', to: 'pages#produ_list', as: 'produ_list'
  get '/mis_productos', to: 'suppliers#my_products', as: 'my_products'
  get '/user_list', to: 'pages#user_list', as: 'user_list'
  get '/suppli_list', to: 'pages#suppli_list', as: 'suppli_list'
  get '/blog', to: 'pages#blog', as: 'blog'

  get '/choose', to: 'products#choose', as: 'choose'

  root 'categories#index'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  img_url    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :sub_categories, dependent: :delete_all
  has_many :products, dependent: :delete_all
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @sub_categories = SubCategory.all
    @all_products = Product.all

    products_in_promotion()

    if params[:concept].present?
      @categories_search = @categories.where("lower(title) like lower(?)", "%#{params[:concept]}%")
      @sub_categories_search = @sub_categories.where("lower(title) like lower(?)", "%#{params[:concept]}%")
      @products_search = @all_products.where("lower(title) like lower(?)", "%#{params[:concept]}%").order("RANDOM()")
      @supplier_search = Supplier.all.where("lower(full_name) like lower(?)", "%#{params[:concept]}%")
    end
  end

  def show
    @subcategories = Category.find(params[:id]).sub_categories

    @products = []
    @subcategories.each do |subcategory|
      @products = @products + subcategory.products
    end
  end

  def new
    @category = Category.new()
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Se creó la categoría exitosamente'
      redirect_to admin_url
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to cate_list_url
    else
      render :edit
    end

  end

  def destroy
    @category = Category.find(params[:id])
    @category.delete

    redirect_to cate_list_url
  end

  def descuentos
    products_in_promotion()
  end

  private
  def category_params
    params.require(:category).permit(:title, :img_url)
  end

  def products_in_promotion
    @products_in_promotion =[]
    @products_with_promotion = Product.where("p_day > ?",0)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/descuentos.html.erb
<div class="product-page">
  <% if @products_with_promotion.length > 0 %>
    <h1 class="category-title-products century-gothic">Productos con descuento del día</h1>

    <div class="products">
      <% @products_with_promotion.each do |product| %>
        <div class="product-container">
          <%=link_to [product.sub_category.category, product.sub_category, product] do%>
            <img src="<%=product.img_url%>" >
            <div class="product-info">
              <h5class="century-gothic"><%=product.title%></h5>
              <h6 class="color-naranja century-gothic-bold">$<%= number_with_delimiter(product.price, :delimiter => '.') %></h6>
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  <%else%>
    <h2 id="no-products">No hay productos con descuentos</h2>
  <% end%>
</div>

<script>
  new DeleteActiveClass();
  new DeleteActiveLinkClass();
</script>

app/views/categories/edit.html.erb
<% if supplier_signed_in? %>
<h1>Editar categoría</h1>

<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

<%= form_for @category, class: "category_form" do |f| %>
  <%= f.text_field :title%> <br> <br>
  <%= f.text_field :img_url %> <br> <br>
  <%= f.submit "Editar categoría" %>
<% end %>
<% else %>
  <h1>No tiene permitido el acceso a esta página</h1>
<% end %>

app/views/categories/index.html.erb
<%if @categories_search != nil || @sub_categories_search != nil || @products_search != nil || @supplier_search != nil %>

  <h4>Encntramos los siguientes resultado</h4>

  <%if @categories_search.length > 0%>
    <div class="category-page">
      <h4>Categorías</h4>
      <div class="categories">
        <% @categories_search.each do |category| %>
          <div class="category-container">
            <%=link_to category_sub_categories_path(category) do%>
              <img src= "<%= category.img_url %>">
              <h5 class= "category-title"><%= category.title %></h5>
            <%end%>
          </div>
        <%end%>
       </div>
      </div>
   <%end%>

   <%if @sub_categories_search.length > 0%>
     <h4>Sub categorías</h4>
     <% @sub_categories_search.each do |sub_category| %>
       <%=link_to category_sub_category_products_path(sub_category.category, sub_category) do%>
         <%=sub_category.title%>
       <%end%>
     <%end%>
  <%end%>

  <%if @products_search.length > 0%>
    <h4>Productos</h4>
    <div class="products">
      <% @products_search.each do |product| %>
        <div class="product-container">
          <%=link_to [product.sub_category.category, product.sub_category, product] do%>
            <img src="<%=product.img_url%>" >
            <div class="product-info">
              <h5 class="century-gothic"><%=product.title%></h5>
              <h6 class="color-naranja century-gothic-bold">$<%= number_with_delimiter(product.price, :delimiter => '.') %></h6>
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  <%end%>

  <%if @supplier_search.length > 0%>
    <h4>Proveedores</h4>
    <% @supplier_search.each do |supplier| %>
      <%=link_to supplier_path(supplier) do%>
        <%=supplier.full_name%>
      <%end%>
    <%end%>
 <%end%>

<%else%>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="3000">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">

        <%= image_tag "carousel/Portadasunopng.png", class:"d-block w-100 img-fluid", alt:"First slide" %>

      </div>
      <div class="carousel-item">
        <%= image_tag "carousel/Portadadospng.png", class:"d-block w-100 img-fluid", alt:"Second slide" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "carousel/portadatrespng.png", class:"d-block w-100 img-fluid", alt:"Third slide" %>


      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="franja"></div>

  <div class="te-ofrecemos">
    <%= image_tag "inicio/itemsboomket.png" %>
  </div>

  <%if user_signed_in?%>
  <h1 class="century-gothic-bold">¡Bienvenido <%=current_user.full_name%>!</h1>
  <%end%>

  <div class="publicity">
    <%if @products_with_promotion.length >0%>
      <div class="publicity-title">
        <h4 class="century-gothic">Descuento del día</h4>
      </div>

      <div class="products-publicity">
        <%random_n = (0..@products_with_promotion.length-1).to_a.shuffle%>
        <%4.times do |i|%>
            <%puts(random_n[i].class)%>
            <%=link_to [@products_with_promotion[random_n[i].to_i].sub_category.category, @products_with_promotion[random_n[i].to_i].sub_category, @products_with_promotion[random_n[i].to_i]] do%>
              <img src="<%=@products_with_promotion[random_n[i].to_i].img_url%>" class="adjust-product-img">
              <div class="publicity-description century-gothic">Precios especiales <br>
                <span class="color-naranja century-gothic-bold">Descuento del <%=@products_with_promotion[random_n[i].to_i].p_day%>%</span> <br>
                Otra cosa super cuca <br>
                Compra ya :)
              </div>
            <%end%>
        <%end%>
      </div>
      <%=link_to descuentos_path, class:"see-more-link" do%>
        <%=image_tag"inicio/Vermaspng.png"%>
      <%end%>
    <%end%>

    <div class="category-page">
      <div class="publicity-title">
        <h4 class="century-gothic">Categorías para ti</h4>
      </div>
      <div class="categories">
        <% @categories.each do |category| %>
          <div class="category-container adjust-category-icon">
            <%=link_to category_path(category) do%>
              <img src= "<%= category.img_url %>">
              <h5 class= "category-title"><%= category.title %></h5>
            <%end%>
          </div>
        <%end%>
      </div>
    </div>

    <%if @all_products.length >0%>
      <div class="publicity-title">
        <h4 class="century-gothic">Recomendado para ti</h4>
      </div>

      <div class="products-publicity">
        <%random_n = (0..@all_products.length-1).to_a.shuffle%>
        <%4.times do |i|%>
          <%=link_to [@all_products[random_n[i].to_i].sub_category.category,@all_products[random_n[i].to_i].sub_category, @all_products[random_n[i].to_i]] do%>
            <img src="<%=@all_products[random_n[i].to_i].img_url%>" class="adjust-product-img">
            <div class="publicity-description century-gothic">
              Precios especiales <br>
              <span class="color-naranja century-gothic-bold"><%=@all_products[random_n[i].to_i].supplier.full_name%></span> <br>
              Otra cosa super cuca <br>
              Compra ya :)
            </div>
          <%end%>
        <%end%>
      </div>
    <%end%>
  </div>

  <div class="medios-pago">
    <h4 class="century-gothic">Multiples medios de pago</h4>
    <%= image_tag "inicio/mediosdepago.png" %>
  </div>


<%end%>
<footer>
  <a href="#">Terminos y condiciones</a>
  <a href="#">Politicas de privacidad</a>
  <%= link_to "Contáctanos", contact_path%>
</footer>
<script>
  new ResizeProductImg();
  new ResizeCategoryIcon();
  // Ni puta idea pero así funciona el carrusel
  $(".owl-carousel").owlCarousel();
  new DeleteActiveClass();
  new DeleteActiveLinkClass();


</script>

app/views/categories/new.html.erb
<% if supplier_signed_in? %>
<h1>Crear categoría</h1>

  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <%= form_for @category, class: "category_form" do |f| %>
    <%= f.text_field :title, placeholder: "Nombre categoría"%> <br> <br>
    <%= f.text_field :img_url, value: "https://drive.google.com/uc?export=view&id=" %> <br> <br>
    <%= f.hidden_field :supplier_id, :value => current_supplier.id %>
    <%= f.submit "Crear categoría" %>
  <% end %>
<% else %>
  <h1>No tiene permitido el acceso a esta página</h1>
<% end %>

app/views/categories/show.html.erb
<div class="product-page">
  <% if @products.length > 0 %>
    <h1 class="category-title-products century-gothic"><%=@products.first.sub_category.category.title%> </h1>

    <div class="products">
      <% @products.shuffle.each do |product| %>
        <div class="product-container">
          <%=link_to [product.sub_category.category, product.sub_category, product] do%>
            <img src="<%=product.img_url%>" >
            <div class="product-info">
              <h5class="century-gothic"><%=product.title%></h5>
              <h6 class="color-naranja century-gothic-bold">$<%= number_with_delimiter(product.price, :delimiter => '.') %></h6>
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  <%else%>
    <h2 id="no-products">No hay productos registrados</h2>
  <% end%>
</div>