config/routes.rb
Rails.application.routes.draw do

  resources :lists
  get 'likes/create'

  get 'likes/destroy'

  get 'favourites/create'

  get 'favourite/create'

  devise_for :suppliers
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'suppliers/:id' => 'suppliers#destroy', :via => :delete, :as => :admin_destroy_supplier

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :sub_categories do
      resources :products do
        resources :favourites, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]

        resources :product_comments, only: [:create]
      end
    end
  end


  resources :order_items
  resource :carts, only: [:show]
  resources :users, only: [:show]
  resources :suppliers, only: [:show, :index] do
    resources :lists
    resources :supplier_comments, only: [:create]
  end



  get '/descuentos', to: 'categories#descuentos', as: 'descuentos'


  get '/alfa', to: 'pages#alfa', as: 'alfa'
  get '/contactanos', to: 'pages#contact', as: 'contact'
  get '/quienessomos', to: 'pages#about', as: 'about'
  get '/administrador', to: 'pages#admin', as: 'admin'
  get '/cate_list', to: 'pages#cate_list', as: 'cate_list'
  get '/produ_list', to: 'pages#produ_list', as: 'produ_list'
  get '/mis_productos', to: 'suppliers#my_products', as: 'my_products'
  get '/user_list', to: 'pages#user_list', as: 'user_list'
  get '/suppli_list', to: 'pages#suppli_list', as: 'suppli_list'
  get '/blog', to: 'pages#blog', as: 'blog'

  get '/choose', to: 'products#choose', as: 'choose'

  root 'categories#index'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  title           :string
#  description     :text
#  price           :integer
#  img_url         :string
#  img_url2        :string
#  img_url3        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  unique          :integer
#  p_day           :float
#  supplier_id     :integer
#  sub_category_id :integer
#  list_id         :integer
#  s1              :string
#  s2              :string
#  s3              :string
#  s4              :string
#  s5              :string
#  s6              :string
#  s7              :string
#  s8              :string
#  s9              :string
#  s10             :string
#  q1              :integer
#  q2              :integer
#  q3              :integer
#  q4              :integer
#  q5              :integer
#  q6              :integer
#  q7              :integer
#  q8              :integer
#  q9              :integer
#  q10             :integer
#  check_unique    :boolean
#  reference       :string
#
# Indexes
#
#  index_products_on_list_id          (list_id)
#  index_products_on_sub_category_id  (sub_category_id)
#  index_products_on_supplier_id      (supplier_id)
#

class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :sub_category
  belongs_to :list

  has_many :likes, dependent: :delete_all
  has_many :users, through: :likes

  has_many :order_items, dependent: :delete_all
  has_many :product_comments, dependent: :delete_all

  validates :list_id,  presence: true
  validates :title, presence: true
  

  def like_by?(user)
    likes.exists?(user: user)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Category.find(params[:category_id]).sub_categories.find(params[:sub_category_id]).products
  end

  def new
    @product = Product.new(sub_category_id: SubCategory.all.first.id)
    @category = Category.find(params[:category_id])
    @list =List.new
    @produ = @list.products.build
  end

  def create
    puts(params[:new_list])
    @category = Category.find(params[:category_id])
    puts(params[:new_list])
    if params[:new_list] == "new"
      puts("----------------CREA UNA NUEVA LISTA----------------------")
      @list= List.new(list_params)

      if @list.save
        @product = @list.products.new(nested_product_params[:products_attributes]["0"].except(:list_id))

        if @product.save
          flash[:notice] = 'Se creó el producto exitosamente'
          redirect_to choose_url
        else
          @produ = @list.products.build(nested_product_params[:products_attributes]["0"].except(:list_id))
          render :new
        end
      else
        @produ = @list.products.build(nested_product_params[:products_attributes]["0"].except(:list_id))
        @product = @list.products.new(nested_product_params[:products_attributes]["0"].except(:list_id))
        render :new
      end
    elsif params[:new_list] == "unique"
      puts("----------------USA UNA LISTA PARA UN PRODUCTO ÚNICO---------------------")
      puts("DEFAULT PRICE: #{params[:default_price]}")
      @list= List.new(title:"Lista producto único",free_shipping: false, promotion:false, quantity:true, price: false, q1:1, sp_q1:params[:default_price], supplier_id: current_supplier.id)

      if @list.save
        @product = @list.products.new(nested_product_params[:products_attributes]["0"].except(:list_id))

        if @product.save
          flash[:notice] = 'Se creó el producto exitosamente'
          redirect_to choose_url
        else
          @produ = @list.products.build(nested_product_params[:products_attributes]["0"].except(:list_id))
          render :new
        end
      else
        @produ = @list.products.build(nested_product_params[:products_attributes]["0"].except(:list_id))
        @product = @list.products.new(nested_product_params[:products_attributes]["0"].except(:list_id))
        render :new
      end
    else
      puts("----------------USA UNA LISTA EXISTENTE----------------------")
      @product = Product.new(nested_product_params[:products_attributes]["0"])
      if @product.save
        flash[:notice] = 'Se creó el producto exitosamente'
        redirect_to choose_url
      else
        puts("#{@product.errors.full_messages} <----------------------------")
        @list= List.new
        @produ = @list.products.build(nested_product_params[:products_attributes]["0"].except(:list_id))
        render :new
      end
    end
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.list_groups.new.order_items.new
  end

  def edit
    @product = Product.find(params[:id])
    @category = Category.find(params[:category_id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to produ_list_url
    else
      render :edit
    end

  end

  def choose
    @categories = Category.all
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to request.referrer
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :img_url, :price,
      :sub_category_id, :list_id, :supplier_id, :p_day, :s1, :s2, :s3, :s4, :s5,
       :s6, :s7, :s8, :s9, :s10, :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9,
       :q10, :check_unique, :unique)
  end
  def nested_product_params
    params.require(:list).permit(products_attributes: [:title, :description,
      :img_url, :price, :sub_category_id, :list_id, :supplier_id, :p_day, :s1,
      :s2, :s3, :s4, :s5, :s6, :s7, :s8, :s9, :s10, :q1, :q2, :q3, :q4, :q5,
      :q6, :q7, :q8, :q9, :q10, :check_unique, :unique])
  end
  def list_params
    params.require(:list).permit(:title, :supplier_id, :free_shipping, :promotion,
       :quantity, :price, :q1, :q2, :q3, :q4, :p_q1, :p_q2, :p_q3, :p_q4, :p1,
       :p2, :p3, :p4, :p_p1, :p_p2, :p_p3, :p_p4, :sq1,:sq2, :sq3, :sq4, :sp_q1,
        :sp_q2, :sp_q3, :sp_q4, :sp1, :sp2, :sp3, :sp4, :sp_p1, :sp_p2, :sp_p3,
        :sp_p4)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/choose.html.erb
<div class="category-page">
  <div class="publicity-title">
    <h4 class="century-gothic">Escoge la categoría a la que pertenece tu producto</h4>
  </div>
  <div class="categories">
    <% @categories.each do |category| %>
      <div class="category-container adjust-category-icon">
        <%=link_to new_category_sub_category_product_path(category,1) do%>
          <img src= "<%= category.img_url %>">
          <h5 class= "category-title"><%= category.title %></h5>
        <%end%>
      </div>
    <%end%>
  </div>
</div>

<script>
  new ResizeCategoryIcon();
</script>

app/views/products/edit.html.erb
<h1>Editar producto</h1>

<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

<% categories = @category.sub_categories.all %>
<% sub_categories_list = [] %>
<% categories.each do |subcategory| %>
  <% selector = [subcategory.title, subcategory.id]%>
  <% sub_categories_list.push(selector) %>
<%end%>

<% lists = current_supplier.lists %>
<% lists_list = [] %>
<% lists.each do |list| %>
  <% selector = [list.title, list.id]%>
  <% lists_list.push(selector) %>
<%end%>

<%= form_for @product, url: category_sub_category_product_path do |f| %>
  <%= f.label "Título:"%> <br>
  <%= f.text_field :title%> <br> <br>
  <%= f.label "Categoría:"%> <br>
  <%= f.select(:sub_category_id, options_for_select(sub_categories_list, [@product.sub_category.title, @product.sub_category.id]), {}, class: 'category-selector') %> <br> <br>
  <%= f.label "Lista:"%> <br>
  <%= f.select(:list_id, options_for_select(lists_list), {}, class: 'category-selector') %> <br> <br>
  <%= f.label "Descripción:"%> <br>
  <%= f.text_area :description%> <br> <br>
  <%= f.label "Link de la imagen:"%> <br>
  <%= f.text_field :img_url%> <br> <br>
  <%= f.label "Precio:"%> <br>
  <%= f.number_field :price, min: 0%> <br> <br>
  <%= f.label "Descuento del día:"%> <br>
  <%= f.number_field :p_day, min: 0%>% <br> <br>
  <%= f.label "Definir tallas y cantidades:"%> <br> <br>

  <%= f.radio_button :check_unique, false%>
  <%= f.label :check_unique, "Cantidades por tallas", :value => "false" %>
  <%= f.radio_button :check_unique, true %>
  <%= f.label :check_unique, "Tamaño único" %> <br><br>

  <%= f.label "Cantidad talla única"%>
  <%= f.number_field :unique, min: 0%> <br> <br>

  <%= f.text_field :s1, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q1, min: 0%> <br> <br>

  <%= f.text_field :s2, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q2, min: 0%> <br> <br>

  <%= f.text_field :s3, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q3, min: 0%> <br> <br>

  <%= f.text_field :s4, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q4, min: 0%> <br> <br>

  <%= f.text_field :s5, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q5, min: 0%> <br> <br>

  <%= f.text_field :s6, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q6, min: 0%> <br> <br>

  <%= f.text_field :s7, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q7, min: 0%> <br> <br>

  <%= f.text_field :s8, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q8, min: 0%> <br> <br>

  <%= f.text_field :s9, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
    <%= f.number_field :q9, min: 0%> <br> <br>

  <%= f.text_field :s10, autocomplete: "off", placeholder: "Talla s/Talla 35/Talla 29-D"%>
  <%= f.number_field :q10, value: 0, min: 0%> <br> <br>
  <%= f.submit "Editar producto" %>
<%end%>

app/views/products/index.html.erb
<div class="product-page">
  <% if @products.length > 0 %>
    <h1 class="category-title-products century-gothic"><%=@products.first.sub_category.title%> </h1>

    <div class="products">
      <% @products.each do |product| %>
        <div class="product-container">
          <%=link_to [product.sub_category.category, product.sub_category, product] do%>
            <img src="<%=product.img_url%>" >
            <div class="product-info">
              <h5class="century-gothic"><%=product.title%></h5>
              <h6 class="color-naranja century-gothic-bold">$<%= number_with_delimiter(product.price, :delimiter => '.') %></h6>
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  <%else%>
    <h2 id="no-products">No hay productos registrados</h2>
  <% end%>
</div>

<script>
  new DeleteActiveClass();
  new DeleteActiveLinkClass();
</script>

app/views/products/show.html.erb
<% sizes_list = [] %>
<% selector = [] %>
<%quantities = [@product.q1.to_i, @product.q2.to_i,@product.q3.to_i,@product.q4.to_i,@product.q5.to_i, @product.q6.to_i, @product.q7.to_i,@product.q8.to_i,@product.q9.to_i,@product.q10.to_i]%>
<%sizes = [@product.s1, @product.s2,@product.s3,@product.s4,@product.s5, @product.s6, @product.s7,@product.s8,@product.s9,@product.s10]%>

<%sizes.each_with_index do |size, i|%>
	<%if quantities[i] > 0%>
		<%selector = [size, quantities[i].to_s+"|"+size]%>
		<% sizes_list.push(selector) %>
	<%end%>
<%end%>

<div>
	<div class="product-to-buy">
		<div class="p-image-specify">
			<img src="<%= @product.img_url %>", class="p-show-img" >
		</div>

		<div class="p-show-specifi">
			<h3 class="arial-bold"><%= @product.title %></h3>

		  <h5 class="arial-bold color-naranja">$<%= @product.price %></h5> <br>
			<%puts(quantities.sum > 0 && @product.check_unique==false)%>
			<%puts("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")%>
			<%puts(@product.unique )%>
			<%puts("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")%>
		  <%if (quantities.sum > 0 && @product.check_unique==false) || (@product.unique > 0 && @product.check_unique==true) %>

			<div>
				<%= form_for(@order_item, remote: true) do |f| %>
			  	<%= f.hidden_field :product_id, value: @product.id %>
					<%if @product.check_unique==false%>
						<div class="form-group">
				  		<h5 class="arial">Tallas disponibles: <%= f.select(:size, options_for_select(sizes_list), {}, class: 'size-selector') %> <br> <br>
				    </div>
					<%else%>
						<%= f.hidden_field :size, value: @product.unique.to_s+"|"+"talla única" %>
					<%end%>
			  	<div class="form-group">
			  		<h5 class="arial">Cantidad: <%= f.number_field :quantity, value: 1, min: 1, class: 'amount', autocomplete: "off" %></h5>
			  	</div>
			  	<%= f.submit "Agregar al carrito", class: 'btn add-to-cart' %>
				<% end %>

				<!-- links, favoritos y me gusta <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< -->
				<%=link_to "Perfil proveedor", supplier_path(@product.supplier)%>
				<% if @product.supplier.favourite_by? current_user %>
					<%=link_to category_sub_category_product_favourite_path(@product.sub_category.category,@product.sub_category,@product, @product.supplier.favourites.where(user: current_user).first), method: :delete, class: "product-upvote upvote-active" do %>
						<span class="upvote-count">Eliminar proveedor de favoritos <%= @product.supplier.favourites.count %></span>
					<% end %>
				<%else%>
					<%= link_to category_sub_category_product_favourites_path(@product.sub_category.category,@product.sub_category,@product), method: :post, class: "product-upvote" do %>
				    <span class="upvote-count">Agregar proveedor a favoritos <i class="fa fa-star"></i> <%= @product.supplier.favourites.count %></span>
				  <% end %>
				<%end%>

				<% if @product.like_by? current_user %>
					<%=link_to category_sub_category_product_like_path(@product.sub_category.category,@product.sub_category,@product, @product.likes.where(user: current_user).first), method: :delete, class: "product-upvote upvote-active" do %>
						<span class="upvote-count">Ya no me gusta <%= @product.likes.count %></span>
					<% end %>
				<%else%>
					<%= link_to category_sub_category_product_likes_path(@product.sub_category.category,@product.sub_category,@product), method: :post, class: "product-upvote" do %>
				    <span class="upvote-count">Me gusta <i class="fa fa-thumbs-up"></i> <%= @product.likes.count %></span>
				  <% end %>
				<%end%>

			</div>
		<% else %>
		  <h1 class="arial">Producto agotado</h1>
		<% end %>
		</div>
	</div>



<!-- Productos recomendados <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< -->
	<div class="recomended-products">
		<%all_products = [] %>
		<h4 class="century-gothic">Otros productos de este proveedor</h4>
		<% @product.supplier.products.all.each do |product| %>
			<%all_products.push(product)%>
		<%end%>
		<%if all_products.length > 5%>
			<%random_n = (0..all_products.length-1).to_a.shuffle%>
			<%4.times do |i|%>
				<div class="product-container" id="recomended-product">
					<%=link_to [all_products[random_n[i]].sub_category.category, all_products[random_n[i]].sub_category, all_products[random_n[i]]] do%>
						<img src="<%=all_products[random_n[i]].img_url%>" >
						<div class="product-info">
							<h5class="century-gothic"><%=all_products[random_n[i]].title%></h5>
							<h6 class="color-naranja century-gothic-bold">$<%= number_with_delimiter(all_products[random_n[i]].price, :delimiter => '.') %></h6>
						</div>
					<%end%>
				</div>
			<%end%>
		<%end%>
	</div>
</div>

<!-- Comentarios <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< -->
<h4 class="our-products century-gothic" id="product-comments-title">Comentarios del producto</h4>
<div class="show-product-comments">
	<% @product.product_comments.each do |comment| %>
	  <div class="panel panel-default">
			<header class="panel-heading"> <b><%= comment.user.full_name %> dice:</b></header>
	    <div class="panel-body"><%= comment.body %></div>
	  </div>
	<% end %>
	<% if signed_in? %>
  <%= form_for [@product.sub_category.category,@product.sub_category, @product, @product.product_comments.build], remote: true do |f| %>
    <div >
      <%= f.text_area :body, placeholder: "Agregar comentario", class:'comment-field' %>
    </div>

    <div class="actions text-left">
      <%= f.submit "Comentar", class: "btn submit-supplier-comment"  %>
    </div>
  <% end %>
<% end %>
</div>

<!-- Tabla de descuentos y envíos <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< -->
<%if (@product.list.free_shipping ==true )&&(@product.list.promotion == false)%>
	<h3><%=@product.list.title%></h3>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Rango por cantidad</th>
				<th scope="col">Procentaje de descuento</th>
				<th scope="col">Costo de envío</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Para todas las cantidades</td>
				<td>Precio único</td>
				<td>Gratis</td>
			</tr>
		</tbody>
	</table>
<%else%>
	<h3><%=@product.list.title%></h3>
	<%if @product.list.quantity == true%>
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Rango por cantidad</th>
					<th scope="col">Procentaje de descuento</th>
					<th scope="col">Costo de envío</th>
				</tr>
			</thead>
			<tbody>
				<%if @product.list.q1 != nil%>
				<tr>
					<td><%=@product.list.q1%> unidades</td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_q1).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_q1).to_s : "Gratis"%></td>
				</tr>
				<%end%>
				<%if @product.list.q2 != nil%>
				<tr>
					<td><%=@product.list.q2%> unidades</td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_q2).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_q2).to_s : "Gratis"%></td>
				</tr>
				<%end%>
				<%if @product.list.q3 != nil%>
				<tr>
					<td><%=@product.list.q3%> unidades</td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_q3).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_q3).to_s : "Gratis"%></td>
				</tr>
				<%end%>
				<%if @product.list.q3 != nil%>
				<tr>
					<td><%=@product.list.q4%> unidades</td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_q4).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_q4).to_s : "Gratis"%></td>
				</tr>
				<%end%>
			</tbody>
		</table>
	<%else%>
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Rango por precio</th>
					<th scope="col">Procentaje de descuento</th>
					<th scope="col">Costo de envío</th>
				</tr>
			</thead>
			<tbody>
				<%if @product.list.p1 != nil%>
				<tr>
					<td>$<%=@product.list.p1%></td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_p1).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_p1).to_s : "Gratis"%></td>
				</tr>
				<%end%>
				<%if @product.list.p2 != nil%>
				<tr>
					<td>$<%=@product.list.p2%></td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_p2).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_p2).to_s : "Gratis"%></td>
				</tr>
				<%end%>
				<%if @product.list.p3 != nil%>
				<tr>
					<td>$<%=@product.list.p3%></td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_p3).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_p3).to_s : "Gratis"%></td>
				</tr>
				<%end%>
				<%if @product.list.p4 != nil%>
				<tr>
					<td>$<%=@product.list.p4%></td>
					<td><%= (@product.list.promotion == true) ? (@product.list.p_p4).to_s+"%" : "Costo fijo"%></td>
					<td><%= (@product.list.free_shipping == false) ? "$"+(@product.list.sp_p4).to_s : "Gratis"%></td>
				</tr>
				<%end%>
			</tbody>
		</table>
	<%end%>
<%end%>

<script>
  new DeleteActiveClass();
	new DeleteActiveLinkClass();
</script>